# Developer's Note: This is a sample _config.yml file offered with
# jekyll-theme-prologue for your convenience. To use it, move it to your
# project's root directory. Please note that the following lines are
# NECESSARY for Prologue to work correctly:
#
# theme: jekyll-theme-prologue
# collections: [sections]
#
# They activate the theme and tell Jekyll to find your homepage content
# in /_sections. Note where "sections" starts with an underscore
# and where it doesn't. The social settings will make links to
# Twitter, etc., but only if you give the URL.
#
# Also, be sure to customize url and baseurl for your site.
#
# ---------------------------------------------------------------
#
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ML-Affairs
subtitle: ...just do it!
description: >- # this means to ignore newlines until "baseurl:"
  Hi! I am Christos; welcome to my website. "ML Engineering Affairs" is the name and its sole purpose is to share my
  thoughts and challenges in the exciting area of Machine Learning, only from an engineering perspective. If you share my
  passion for applied data science and are looking for a refreshing look at things, then you are at the right place.
author: Christos Hadjinikolis
email: christos.hadjinikolis@gmail.com
avatar: assets/images/profile.jpg

# You'll want to customize url and baseurl for your own site:
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://christos-hadjinikolis.github.io/" # the base hostname & protocol for your site

# Social settings
# Make sure to include the full url including protocol, e.g. https://github.com/chrisbobbe
twitter_url: https://twitter.com/chatzinikolis
facebook_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/christoshadjinikolis/
github_url: https://github.com/Christos-Hadjinikolis
stackoverflow_url: https://stackoverflow.com/users/6171195/christos-hadjinikolis
pinterest_url:
slack_url:
dribbble_url:

# Google Analytics Tracking ID goes here:
google_analytics: UA-173020434-1

# The following settings are NECESSARY for the Prologue theme to run:
theme: jekyll-theme-prologue
collections: [sections]
